### ISSUE TITLE
Would it be possible to port this library to ARM-based Arduino boards (Zero, MKR1000...)?

### ISSUE THREAD

**Issue by q2dg** [josepbordesjove/FLiR-lepton#1]
Thanks!

**Comment by josepbordesjove** [comment]
Yes, I am pretty sure that is possible, but I was working with the camera while I was working at a public university and the camera belongs to them. I am going to ask them the camera and if they lend the camera I'd try to adapt it.

**Comment by josepbordesjove** [comment]
I am so sorry to say that, but I was not able to get the camera and develop the updated version of the code. But I would be pleased to help you with the development of this!

**Comment by josepbordesjove** [comment]
Did you try to develop this project?

**Comment by q2dg** [comment]
No, sorry

**Comment by josepbordesjove** [comment]
The project is not going to be updated by my part... If anyone wants to do it, I'll help in whatever is needed!
