### ISSUE TITLE
.h file

### ISSUE THREAD

**Issue by berry0805** [josepbordesjove/FLiR-lepton#2]
Where can i find the "wire.h" and "spi.h"？Thanks.

**Comment by josepbordesjove** [comment]
This is not C, if you notice the files are .ino so you don't need header files for the Arduino. I also developed a version for the Raspberry (https://github.com/josepbordesjove/LeptonCapture) if you need anything else don't hesitate to ask again.

P.D: Maybe I misunderstood your question!

**Comment by berry0805** [comment]
I appreciate for your help.

**Comment by berry0805** [comment]
I want to know whether the Lepton starts to transfer the data of frame once CS is low and SCLK is provided .

**Comment by josepbordesjove** [comment]
Have you tried to connect some kind of electronic measurement device to check it? also you may print an output with the terminal, hope it helps!
